name: FreeRDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 600
    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extracting Ngrok Files.
      run: Expand-Archive ngrok.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Write-Host '[+] Setting up firewall for Remote Desktop...'
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Start-Job -Command "Enable-NetFirewallRule -DisplayGroup 'Remote Desktop'"
        Write-Host '[+] Enable RDP user login...'
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Creating user account.
      run: |
        Write-Host '[+] Creating user FreeRDP...'
        New-LocalUser -Name 'FreeRDP' -Password (ConvertTo-SecureString 'SuperSecurePassword1234' -AsPlainText -Force) -FullName 'FreeRDP by Plyrs'
        Write-Host '[+] Adding to Administrator group...'
        Add-LocalGroupMember -Group 'Administrators' -Member 'FreeRDP'
        Write-Host '[+] Enabling user...'
        Enable-LocalUser -Name 'FreeRDP'
        Write-Host '[+] Deleting user "installer"...'
        Remove-LocalUser -Name 'installer'
    - name: Setting up desktop.
      run: |
        Write-Host '[+] Disabling auto hide tray icons...'
        Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer' -name "EnableAutoTray" -Value 0
        Write-Host '[+] Setting small start icons...'
        Set-ItemProperty -Path "registry::hkey_users\$((New-Object System.Security.Principal.NTAccount('FreeRDP')).Translate([System.Security.Principal.SecurityIdentifier]).Value)\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -name "TaskbarSmallIcons" -Value 1
        Write-Host '[+] Setting black wallpaper...'
        Invoke-WebRequest https://raw.githubusercontent.com/Plyrs1/FreeRDP/main/wallpaper.jpg -OutFile wallpaper.jpg
        Set-ItemProperty -Path "registry::hkey_users\$((New-Object System.Security.Principal.NTAccount('FreeRDP')).Translate([System.Security.Principal.SecurityIdentifier]).Value)\Control Panel\Desktop" -Name 'Wallpaper' -Value 'D:\a\wallpaper.jpg'
        # Start-Process 'RUNDLL32.EXE' 'user32.dll,UpdatePerUserSystemParameters'
        # Stop-Process -name explorer -force
        # Start-Process explorer
    - name: Finishing up.
      run: |
        Write-Host '[+] Starting audiosrv...'
        Start-Process 'sc' 'config audiosrv start= auto'
        Start-Process 'sc' 'start audiosrv'
        Write-Host '[+] Granting folder permission...'
        Start-Process 'ICACLS' 'C:\Windows\Temp /grant FreeRDP:F'
        Start-Process 'ICACLS' 'C:\Windows\installer /grant FreeRDP:F'
        Write-Host '[+] Checking ngrok...'
        Get-Process -Name 'ngrok'
        Write-Host '[+] IP :' ((Invoke-WebRequest -Uri http://localhost:4040/api/tunnels -ContentType "application/json").Content | ConvertFrom-Json).tunnels[0].public_url
        Write-Host '[+] User : FreeRDP'
        Write-Host '[+] Pass : SuperSecurePassword1234'
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://raw.githubusercontent.com/Plyrs1/FreeRDP/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
